spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/covid9_server?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.design.covid9server.entity

#showSql
logging:
  level:
    com:
      design:
        covid9server:
          mapper : debug